# Generated by Django 4.2.6 on 2023-10-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_alter_transaccion_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.IntegerField(max_length=1000),
        ),
    ]
