# Generated by Django 4.2.6 on 2023-10-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_alter_transaccion_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.IntegerField(max_length=100),
        ),
    ]
